from .user import UserViewSet
from .produto import ProdutoViewSet
from .fabricante import FabricanteViewSet
from .avaliacao import AvaliacaoViewSet
from .endereco import EnderecoViewSet
from .telefone import TelefoneViewSet
from .despesa import DespesaViewSet
from .cupom import CupomViewSet
from .compra import CompraViewSet
from .MovimentacaoFinanceira import MovimentacaoViewSet