# Generated by Django 5.0.6 on 2024-09-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_fabricante"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="fabricante",
            field=models.ManyToManyField(blank=True, related_name="produtos", to="core.fabricante"),
        ),
    ]
