# Generated by Django 5.0.6 on 2024-09-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_endereco"),
    ]

    operations = [
        migrations.AddField(
            model_name="fabricante",
            name="endereco",
            field=models.ManyToManyField(blank=True, related_name="endereco_fabricante", to="core.endereco"),
        ),
    ]
