# Generated by Django 5.0.6 on 2024-09-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_fabricante_endereco"),
    ]

    operations = [
        migrations.AddField(
            model_name="fabricante",
            name="cnpj",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fabricante",
            name="email",
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="fabricante",
            name="site",
            field=models.URLField(blank=True, null=True),
        ),
    ]
