# Generated by Django 5.0.6 on 2024-09-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_produto_fabricante_produto_descricao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="endereco",
            name="bairro",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="endereco",
            name="cidade",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="endereco",
            name="complemento",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="endereco",
            name="estado",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="endereco",
            name="numero",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="endereco",
            name="rua",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
