# Generated by Django 5.0.6 on 2024-09-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_endereco_bairro_endereco_cidade_endereco_complemento_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Telefone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ddd", models.CharField(max_length=3)),
                ("numero", models.CharField(max_length=10)),
            ],
        ),
    ]
