# Generated by Django 5.0.6 on 2024-09-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_telefone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="endereco",
            field=models.ManyToManyField(blank=True, related_name="endereco_usuario", to="core.endereco"),
        ),
        migrations.AddField(
            model_name="user",
            name="telefone",
            field=models.ManyToManyField(blank=True, related_name="telefone_usuario", to="core.telefone"),
        ),
    ]
