# Generated by Django 5.0.6 on 2024-09-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_user_endereco_user_telefone"),
    ]

    operations = [
        migrations.AddField(
            model_name="fabricante",
            name="telefone",
            field=models.ManyToManyField(blank=True, related_name="telefone_fabricante", to="core.telefone"),
        ),
    ]
