# Generated by Django 5.0.6 on 2024-09-25 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_avaliacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cupom",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("porcentagem_desconto", models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                (
                    "criador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="cupom", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
