# Generated by Django 5.0.6 on 2024-09-25 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_cupom"),
    ]

    operations = [
        migrations.CreateModel(
            name="Foto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("imagem_url", models.URLField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="foto", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
