# Generated by Django 5.0.6 on 2024-09-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="metodo_Pagamento",
            field=models.IntegerField(choices=[(1, "Pix"), (2, "Cartão")], default=1),
        ),
    ]
