# Generated by Django 5.1.1 on 2024-09-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_compra_metodo_pagamento"),
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="foto",
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name="+", to="uploader.image"),
        ),
    ]
