# Generated by Django 5.1.1 on 2024-09-29 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_produto_foto"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Foto",
        ),
    ]
