# Generated by Django 5.1.1 on 2024-09-29 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_delete_foto"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaBateria",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("capacidade", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tensaoNominal", models.DecimalField(decimal_places=2, max_digits=5)),
                ("vidaUtil", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CategoriaCabos",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("material", models.CharField(max_length=100)),
                ("comprimento", models.DecimalField(decimal_places=2, max_digits=10)),
                ("isolamento", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CategoriaConectores",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("tensaoNominal", models.DecimalField(decimal_places=2, max_digits=5)),
                ("correnteNominal", models.DecimalField(decimal_places=2, max_digits=5)),
                ("material", models.CharField(max_length=100)),
                ("acabamento", models.CharField(blank=True, max_length=100, null=True)),
                ("comprimento", models.DecimalField(decimal_places=2, max_digits=10)),
                ("largura", models.DecimalField(decimal_places=2, max_digits=10)),
                ("altura", models.DecimalField(decimal_places=2, max_digits=10)),
                ("diametro", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("profundidade", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CategoriaEstrutura",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("largura", models.DecimalField(decimal_places=2, max_digits=10)),
                ("altura", models.DecimalField(decimal_places=2, max_digits=10)),
                ("capacidadeCarga", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CategoriaInversor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("potencia", models.IntegerField()),
                ("eficiencia", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CategoriaPlacaSolar",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("tipoCelula", models.CharField(max_length=100)),
                ("potencia", models.IntegerField()),
                ("eficiencia", models.FloatField()),
                ("largura", models.DecimalField(decimal_places=2, max_digits=10)),
                ("altura", models.DecimalField(decimal_places=2, max_digits=10)),
                ("peso", models.DecimalField(decimal_places=2, max_digits=10)),
                ("temperaturaOperacao", models.DecimalField(decimal_places=2, max_digits=5)),
                ("toleranciaPotencia", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CategoriaKitSolar",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("tipo", models.IntegerField(choices=[(1, "On-grid"), (2, "Off-grid")], default=1)),
                (
                    "bateria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bateria",
                        to="core.categoriabateria",
                    ),
                ),
                (
                    "inversor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inversor",
                        to="core.categoriainversor",
                    ),
                ),
                ("placa", models.ManyToManyField(blank=True, related_name="kit_placa", to="core.categoriaplacasolar")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
