# Generated by Django 5.1.1 on 2024-09-29 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_categoriabateria_categoriacabos_categoriaconectores_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(blank=True, max_length=100, null=True)),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "tipo",
                    models.IntegerField(
                        choices=[
                            (1, "Placa Solar"),
                            (2, "Inversor"),
                            (3, "Conectores"),
                            (4, "Cabos"),
                            (5, "Estrutura"),
                            (6, "Bateria"),
                            (7, "Kit solar"),
                            (8, "Micro Inversores"),
                        ],
                        default=1,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="categoriakitsolar",
            name="bateria",
        ),
        migrations.DeleteModel(
            name="CategoriaCabos",
        ),
        migrations.DeleteModel(
            name="CategoriaConectores",
        ),
        migrations.DeleteModel(
            name="CategoriaEstrutura",
        ),
        migrations.RemoveField(
            model_name="categoriakitsolar",
            name="inversor",
        ),
        migrations.RemoveField(
            model_name="categoriakitsolar",
            name="placa",
        ),
        migrations.AddField(
            model_name="produto",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="categoria",
                to="core.categoria",
            ),
        ),
        migrations.DeleteModel(
            name="CategoriaBateria",
        ),
        migrations.DeleteModel(
            name="CategoriaInversor",
        ),
        migrations.DeleteModel(
            name="CategoriaKitSolar",
        ),
        migrations.DeleteModel(
            name="CategoriaPlacaSolar",
        ),
    ]
