# Generated by Django 5.1.1 on 2024-09-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_categoria_remove_categoriakitsolar_bateria_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Despesa",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("valor", models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("data", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MovimentacaoFinanceira",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tipo", models.IntegerField(choices=[(1, "Entrada"), (2, "Saída")])),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descricao", models.CharField(max_length=200)),
                ("data", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
