# Generated by Django 5.1.1 on 2024-10-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_despesa_movimentacaofinanceira"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="quantidade",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
