# Generated by Django 5.1.1 on 2024-10-05 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_produto_quantidade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoria",
            name="tipo",
        ),
    ]
