# Generated by Django 5.1.1 on 2024-10-05 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_produto_descricao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cupom",
            name="criador",
        ),
    ]
