# Generated by Django 4.2.16 on 2024-11-01 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_user_foto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orcamento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("consumoMensal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("gastoSemPlaca", models.DecimalField(decimal_places=2, max_digits=10)),
                ("estado", models.CharField(blank=True, max_length=255)),
                ("irradiacao", models.DecimalField(decimal_places=2, max_digits=10)),
                ("potenciaPlaca", models.DecimalField(decimal_places=5, max_digits=10)),
                ("areaDisponivel", models.DecimalField(decimal_places=2, max_digits=10)),
                ("gastoComPlaca", models.DecimalField(decimal_places=2, max_digits=10)),
                ("playback", models.DecimalField(decimal_places=1, max_digits=10)),
                ("porcetangemReducao", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orcamento",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
