# Generated by Django 4.2.16 on 2024-11-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_orcamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="orcamento",
            name="qtdPlaca",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
