# Generated by Django 4.2.16 on 2024-11-02 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_orcamento_qtdplaca"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="cupom",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.cupom"
            ),
        ),
    ]
