# Generated by Django 4.2.16 on 2024-11-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_compra_cupom"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="desconto",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
