# Generated by Django 4.2.16 on 2024-11-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_compra_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compra",
            name="total",
        ),
        migrations.AlterField(
            model_name="compra",
            name="desconto",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
