# Generated by Django 4.2.16 on 2024-11-04 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_remove_compra_total_alter_compra_desconto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produto",
            old_name="fabricantes",
            new_name="fabricante",
        ),
    ]
