# Generated by Django 4.2.16 on 2024-11-06 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_remove_user_telefone_user_telefone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="telefone",
        ),
    ]
