# Generated by Django 4.2.16 on 2024-11-06 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_remove_user_telefone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telefone",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.telefone"
            ),
        ),
    ]
