# Generated by Django 4.2.16 on 2024-11-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_user_telefone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fabricante",
            name="cnpj",
            field=models.CharField(max_length=14),
        ),
    ]
