# Generated by Django 4.2.16 on 2024-11-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_alter_fabricante_cnpj"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fabricante",
            name="cnpj",
            field=models.CharField(),
        ),
    ]
