# Generated by Django 4.2.16 on 2024-11-14 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_alter_fabricante_cnpj"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produto",
            old_name="garantia_meses",
            new_name="garantia_anos",
        ),
    ]
