# Generated by Django 4.2.16 on 2024-12-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_rename_garantia_meses_produto_garantia_anos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacao",
            name="nota",
            field=models.IntegerField(),
        ),
    ]
