# Generated by Django 4.2.16 on 2024-12-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_alter_avaliacao_nota"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compra",
            name="metodo_Pagamento",
            field=models.IntegerField(choices=[(1, "Pix"), (2, "Cartão")], default=1, null=True),
        ),
    ]
